function menu()
{
document.writeln("<ul class=\"menu\">");
document.writeln("<center>");
document.writeln("<div class=\"sombreada_css3\"><font color=\"#FFFFFF\" face=\"Helvetica Neue,Helvetica,Arial,sans-serif\" size=\"2\"><i class=\"far fa-calendar-alt\"></i><b>  SABADO 12 DE FEBRERO DEL 2022</b></font></div></center>");
document.writeln("<li class=\"FRA\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">17:00</span>Montpellier vs Lille</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal2/arenasports.html\" rel=\"nofollow\" target=\"streamframe\">Arena Sports Premium<span>Calidad 720p</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal2/beines.html\" rel=\"nofollow\" target=\"streamframe\">Bein Sports Español<span>Calidad 720p</span></a></li>	");
document.writeln("</ul>	");
document.writeln("</li>");
document.writeln("<li class=\"FIFA\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">17:30</span>Chelsea vs Palmeiras Mundial de Clubes</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal/tntsport1.html\" rel=\"nofollow\" target=\"streamframe\">TNT Sports<span>Calidad 720p</span></a></li>	");
document.writeln("<li class=\"subitem1\"><a href=\"/canal2/foxsportsdeporte.html\" rel=\"nofollow\" target=\"streamframe\">Fox Sports Deportes UK<span>Calidad 720p</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal2/f2us.html\" rel=\"nofollow\" target=\"streamframe\">FS 2 US<span>Calidad 720p</span></a></li>");
document.writeln("</ul>	");
document.writeln("</li>");
document.writeln("<li class=\"ENG\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">18:30</span>Norwich City vs Manchester</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal/espn1.html\" rel=\"nofollow\" target=\"streamframe\">ESPN<span>Calidad 720p</span></a></li>	");
document.writeln("</ul>	");
document.writeln("</li>");
document.writeln("<li class=\"ES\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">18:30</span>Rayo Vallecano vs Osasuna</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9obHMuY2MudGFwcGxpdmUuY29tL2xpdmUvNjFkZjFlOWE0ZjU1NGM5M2ZkZDJlN2MyL3N0cmVhbS5tM3U4\" rel=\"nofollow\" target=\"streamframe\">Directv Sports<span>Calidad 720p</span></a></li>	");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9ha2FtYWkyLWJyLmNkbi5ib295YWgubGl2ZS9obHMvMTUwMDAyNC85ODA3NzkzMS5tM3U4\" rel=\"nofollow\" target=\"streamframe\">ESPN Brasil<span>Calidad 720p</span></a></li>	");
document.writeln("</ul>	");
document.writeln("</li>");
document.writeln("<li class=\"ALE\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">18:30</span>Bayer Leverkusen vs Stuttgart</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal/espn4.html\" rel=\"nofollow\" target=\"streamframe\">ESPN 4<span>Calidad 720p</span></a></li>	");
document.writeln("</ul>	");
document.writeln("</li>");
document.writeln("<li class=\"BOL\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">20:00</span>Always Ready vs Royal Pari</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal3/tigo.html\" rel=\"nofollow\" target=\"streamframe\">Tigo Sports<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"BOL\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">20:00</span>Wilstermann vs Blooming</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9jZG4ubGl2ZXBlZXIuY29tL2hscy81ODY4NTRlbXIxMnE4OXV0LzFfMC9pbmRleC5tM3U4\" rel=\"nofollow\" target=\"streamframe\">Tigo Sports<span>Calidad 720p</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/ft.html?get=aHR0cHM6Ly9jZG4ubGl2ZXBlZXIuY29tL2hscy81ODY4NTRlbXIxMnE4OXV0LzFfMC9pbmRleC5tM3U4\" rel=\"nofollow\" target=\"streamframe\">Tigo Sports<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"FRA\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">21:00</span>Lyon vs. Niza</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal/espn2.html\" rel=\"nofollow\" target=\"streamframe\">ESPN 2<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"ES\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">21:00</span>Atlético Madrid vs. Getafe</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal/espn1.html\" rel=\"nofollow\" target=\"streamframe\">ESPN<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>		");
document.writeln("<span class=\"t\">21:00</span>Huracán vs. Lanús</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal/tntsport1.html\" rel=\"nofollow\" target=\"streamframe\">TNT Sports<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"NBA\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>	");
document.writeln("NBA: Transmisión");
document.writeln("<span class=\"t\">01:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"https://dqm8bvwrahfi8.cloudfront.net/hls/cavaliers/playlist.m3u8\" target=\"_blank\">Cavaliers vs. Spurs (M3U8)<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"https://dqm8bvwrahfi8.cloudfront.net/hls/hornets/playlist.m3u8\" target=\"_blank\">Hornets vs. Bulls (M3U8)<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"https://dqm8bvwrahfi8.cloudfront.net/hls/thunder/playlist.m3u8\" target=\"_blank\">Thunder vs. Raptors (M3U8)<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal5/tnt01.html\" rel=\"nofollow\" target=\"streamframe\">TNT OP 1<span>Calidad 720p</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal5/tnt02.html\" rel=\"nofollow\" target=\"streamframe\">TNT OP 2<span>Calidad 720p</span></a></li>");
document.writeln("<p><strong><i style=\"color:red\">OPCIÓN M3U8:</strong></i> Para que esta opción funcione en PC, necesitás instalar la extensión <strong style=\"color:red\">Reproductor M3U8 - HLS Player</strong> en tu navegador. (<a href=\"https://chrome.google.com/webstore/detail/lcipembjfkmeggpihdpdgnjildgniffl\" target=\"_blank\">Google Chrome-Brave</a> / <a href=\"https://addons.mozilla.org/es/firefox/addon/native_hls_playback/\" target=\"_blank\">Mozilla Firefox</a>)</p>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"CH\"><a href=\"#\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>	");
document.writeln("<span class=\"\"><i class=\"fa-solid fa-play\"></i> TV</span>Musica Las 24 Horas</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal3/foxmix.html\" rel=\"nofollow\" target=\"streamframe\">Portal Fox mix<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"INTER\"><a href=\"\">");
document.writeln("<div class=\"icon\"><span2 style=\"color: white;\"><b><span1 style=\"background-color: red;border-radius:5px\"> VIVO <br /></span1></b></span2></div>	");
document.writeln("<span class=\"\"><i class=\"fa-solid fa-tv\"></i> TV</span>BUSCAR MAS CANALES</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"\" target=\"_blank\"> Pronto Canales 24 Horas<span>Calidad SD</span></a></li>	");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("</ul>");
}

