function menu()
{
document.writeln("<ul class=\"menu\">");
document.writeln("<center>");
document.writeln("<div class=\"sombreada_css3\"><font color=\"#FFFFFF\" face=\"Helvetica Neue,Helvetica,Arial,sans-serif\" size=\"2\"><i class=\"far fa-calendar-alt\"></i><b>  AGENDA VIERNES 11 DE MARZO DE 2022</b></font></div></center>");
document.writeln("<li class=\"FUT\"><a href=\"#\">");
document.writeln("Estudiantes Mérida vs. Carabobo");
document.writeln("<span class=\"t\">20:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"canal1.html\">Canal I<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"HOL\"><a href=\"#\">");
document.writeln("Eredivise: Cambuur vs. Ajax");
document.writeln("<span class=\"t\">20:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"espn2.html\">ESPN 2<span>Calidad 720p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"sporttv2.html\">Sport TV 2 HD PT<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"ES\"><a href=\"#\">");
document.writeln("Atlético Madrid vs. Cádiz");
document.writeln("<span class=\"t\">21:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"bein1.html\">beIN Sports 1 FR<span>Calidad 720p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"eleven1.html\">Eleven Sports 1 PT<span>Calidad 720p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"tv2sportx.html\">TV2 Sport X DK<span>Calidad 720p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"tv2sportpremium.html\">TV2 Sport Premium NO<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"FRA\"><a href=\"#\">");
document.writeln("Lille vs. Saint-Étienne");
document.writeln("<span class=\"t\">21:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"eleven2.html\">Eleven Sports 2 PT<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"POR\"><a href=\"#\">");
document.writeln("Benfica vs. Vizela");
document.writeln("<span class=\"t\">21:15</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"http://diex01.herokuapp.com/goltv1.html\">Gol TV<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"CH\"><a href=\"#\">");
document.writeln("Primera División: La Serena vs. Cobresal");
document.writeln("<span class=\"t\">22:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"tntsportchile.html\">TNT Sports Chile<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Primera Nacional: Almagro vs. Tristán Suárez");
document.writeln("<span class=\"t\">22:05</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"tycsport.html\">TyC Sports<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Arsenal vs. Vélez");
document.writeln("<span class=\"t\">23:15</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"foxpremium.html\">FOX Sports Premium<span>Calidad 1080p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"URU\"><a href=\"#\">");
document.writeln("Cerrito vs Rentistas");
document.writeln("<span class=\"t\">23:15</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"vtv+.html\">VTV +<span>Calidad 1080p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Belgrano vs. San Martín (SJ)	");
document.writeln("<span class=\"t\">00:10</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"tycsport.html\">TyC Sports<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"FUT\"><a href=\"#\">");
document.writeln("Monagas vs. Portuguesa");
document.writeln("<span class=\"t\">00:30</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"canal1.html\">Canal I<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"ECUA\"><a href=\"#\">");
document.writeln("Liga Pro: Aucas vs. Deportivo Cuenca");
document.writeln("<span class=\"t\">01:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"goltv1.html\">Gol TV<span>Calidad 720p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Estudiantes (RC) vs. Def. de Belgrano");
document.writeln("<span class=\"t\">01:30</span></a>");
document.writeln("<ul>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Platense vs. Patronato");
document.writeln("<span class=\"t\">01:30</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"foxpremium.html\">FOX Sports Premium<span>Calidad 1080p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"WWE\"><a href=\"#\">");
document.writeln("SmackDown WWE Lucha libre");
document.writeln("<span class=\"t\">02:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"foxsport2.html\">Fox Sports 2<span>Calidad 1080p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"foxsport2mx.html\">Fox Sports MX<span>Calidad 1080p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"MEX\"><a href=\"#\">");
document.writeln("Liga MX: Necaxa vs. Querétaro");
document.writeln("<span class=\"t\">02:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"tudn.html\">TUDN<span>Calidad 1080p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"azteca7.html\">Azteca 7<span>Calidad 1080p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"MEX\"><a href=\"#\">");
document.writeln("Liga MX: FC Juárez vs. Atlas");
document.writeln("<span class=\"t\">04:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"tudn.html\" target=\"_blank\">TUDN<span>Calidad 1080p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"azteca7.html\" target=\"_blank\">Azteca 7<span>Calidad 1080p</span></a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"MEX\"><a href=\"#\">");
document.writeln("Liga MX: Monterrey vs. Mazatlán");
document.writeln("<span class=\"t\">04:06</span></a>");
document.writeln("<ul>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<li class=\"NBA\"><a href=\"#\">");
document.writeln("NBA: Transmisión");
document.writeln("<span class=\"t\">01:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"https://d3bh6k6cdgaj10.cloudfront.net/hls/hornets/playlist.m3u8\" target=\"_blank\">Hornets vs. Nets (M3U8)<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"https://d3bh6k6cdgaj10.cloudfront.net/hls/pacers/playlist.m3u8\" target=\"_blank\">Pacers vs. Cavaliers (M3U8)<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"https://d3bh6k6cdgaj10.cloudfront.net/hls/magic/playlist.m3u8\" target=\"_blank\">Magic vs. Suns (M3U8)<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"https://d3bh6k6cdgaj10.cloudfront.net/hls/TNT/playlist.m3u8\" target=\"_blank\">Grizzlies vs. Pelicans (M3U8)<span>Calidad SD</span></a></li> ");
document.writeln("<li class=\"subitem1\"><a href=\"/canal5/tnt01.html\" target=\"iframe\">TNT OP 1<span>Calidad 480p</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal5/tnt01.html\" target=\"iframe\">TNT OP 2<span>Calidad 720p</span></a></li>");
document.writeln("<p><strong><i style=\"color:red\">OPCIÓN M3U8:</strong></i> Para que esta opción funcione en PC, necesitás instalar la extensión <strong style=\"color:red\">Reproductor M3U8 - HLS Player</strong> en tu navegador. (<a href=\"https://chrome.google.com/webstore/detail/lcipembjfkmeggpihdpdgnjildgniffl\" target=\"iframe\">Google Chrome-Brave</a> / <a href=\"https://addons.mozilla.org/es/firefox/addon/native_hls_playback/\" target=\"iframe\">Mozilla Firefox</a>)</p>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"CH\"><a href=\"#\">	");
document.writeln("<span class=\"\"><i class=\"fa-solid fa-play\"></i> TV</span>Musica Las 24 Horas</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal3/foxmix.html\" target=\"iframe\">Portal Fox mix<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"INTER\"><a href=\"\">	");
document.writeln("<span class=\"\"><i class=\"fa-solid fa-tv\"></i> TV</span>CANALES 24</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/ft.html?get=aHR0cHM6Ly92aWRlb3N0cmVhbWluZy5jbG91ZHNlcnZlcmxhdGFtLmNvbTo0NDMvRWxDaGF2b3R2L0VsQ2hhdm90di9wbGF5bGlzdC5tM3U4\" target=\"iframe\">Chavo del 8<span>Calidad SD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlLWxpdmUxMi1zbC5jdmF0dHYuY29tLmFyL2xpdmUvYzNlZHMvTmF0R2VvSEQvU0FfU0FHRU1DT00vTmF0R2VvSEQubTN1OA==\" target=\"iframe\">National Geographic<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlOS1oci5jdmF0dHYuY29tLmFyL2xpdmUvYzNlZHMvTmF0R2VvV2lsZEhEL1NBX1NBR0VNQ09NL05hdEdlb1dpbGRIRC5tM3U4\" target=\"iframe\">NATGEO WILD<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlOS1oci5jdmF0dHYuY29tLmFyLy9saXZlL2MzZWRzL1NwYWNlL1NBX1NBR0VNQ09NL1NwYWNlLm0zdTg=\" target=\"iframe\">SPACE<span>Calidad HD</span></a></li>	");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlOS1oci5jdmF0dHYuY29tLmFyLy9saXZlL2MzZWRzL1ROVF9IRF9BcmcvU0FfU0FHRU1DT00vVE5UX0hEX0FyZy5tM3U4\" target=\"iframe\">TNT<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlOS1oci5jdmF0dHYuY29tLmFyL2xpdmUvYzJsaXZlL0ZveF9MaWZlL1NBX1NBR0VNQ09NL0ZveF9MaWZlLm0zdTg=\" target=\"iframe\">STAR LIFE<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlOS1oci5jdmF0dHYuY29tLmFyLy9saXZlL2xpdmUvRm94Q2xhc3NpY3MvU0FfU0FHRU1DT00vRm94Q2xhc3NpY3MubTN1OA==\" target=\"iframe\">STAR CLASSICS<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlOS1oci5jdmF0dHYuY29tLmFyLy9saXZlL2MzZWRzL0hCT0hEL1NBX1NBR0VNQ09NL0hCT0hELm0zdTg=\" target=\"iframe\">HBO<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlLWxpdmUxNS1zbC5jdmF0dHYuY29tLmFyL2xpdmUvYzdlZHMvUGFyYW1vdW50L1NBX1NBR0VNQ09NL1BhcmFtb3VudC5tM3U4\" target=\"iframe\">PARAMOUNT HD<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlLWxpdmUxNC1oci5jdmF0dHYuY29tLmFyL2xpdmUvYzNlZHMvRGlzY292ZXJ5SEQvU0FfU0FHRU1DT00vRGlzY292ZXJ5SEQubTN1OA==\" target=\"iframe\">DISCOVERY<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlLWxpdmUxNC1oci5jdmF0dHYuY29tLmFyL2xpdmUvYzNlZHMvQ2FydG9vbk5ldHdvcmsvU0FfU0FHRU1DT00vQ2FydG9vbk5ldHdvcmsubTN1OA==\" target=\"iframe\">Cartoon Network<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlMDItZmRvLXB5LmN2YXR0di5jb20uYXIvbGl2ZS9jN2Vkcy9BWE5IRC9TQV9TQUdFTUNPTS9BWE5IRC5tM3U4\" target=\"iframe\">AXN<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlMDItZmRvLXB5LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9DYW5hbF9kZV9sYXNfZXN0cmVsbGFzL1NBX1NBR0VNQ09NL0NhbmFsX2RlX2xhc19lc3RyZWxsYXMubTN1OAo=\" target=\"iframe\">Las estrellas<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlMDItZmRvLXB5LmN2YXR0di5jb20uYXIvbGl2ZS9jM2Vkcy9EaXNuZXlDaGFubmVsSEQvU0FfU0FHRU1DT00vRGlzbmV5Q2hhbm5lbEhELm0zdTgKCg==\" target=\"iframe\">Disney Channel HD<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlMDItZmRvLXB5LmN2YXR0di5jb20uYXIvbGl2ZS9jM2Vkcy9DaW5lY2FuYWxIRC9TQV9TQUdFTUNPTS9DaW5lY2FuYWxIRC5tM3U4Cgo=\" target=\"iframe\">Cine Canal HD<span>Calidad HD</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/embed/go.html?get=aHR0cHM6Ly9lZGdlMDItZmRvLXB5LmN2YXR0di5jb20uYXIvbGl2ZS9jN2Vkcy9JRC9TQV9TQUdFTUNPTS9JRC5tM3U4CgoK\" target=\"iframe\">DISCOVERY ID<span>Calidad HD</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("</ul>");
}
