function menu()
{
document.writeln("<ul class=\"menu\">");
document.writeln("<center>");
document.writeln("<div class=\"sombreada_css3\"><font color=\"#FFFFFF\" face=\"Helvetica Neue,Helvetica,Arial,sans-serif\" size=\"2\"><i class=\"far fa-calendar-alt\"></i><b>  AGENDA VIERNES 15 DE ABRIL DE 2022</b></font></div></center>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Tigre vs. Huracán Copa de La Liga Profesional");
document.writeln("<span class=\"t\">20:30</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"http://diexsport.herokuapp.com/tntsport.html\" target=\"_blank\">TNT Sports<span>Calidad 1080p</span></a> </ul>");
document.writeln("</li>");
document.writeln("<li class=\"ENG\"><a href=\"#\">");
document.writeln("Derby County vs. Fulham Championship");
document.writeln("<span class=\"t\">21:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"bein5.html\" target=\"_blank\">BeIN Sports Max 5 FR<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"PE\"><a href=\"#\">");
document.writeln("UTC Cajamarca vs Academia Cantolao");
document.writeln("<span class=\"t\">21:30</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"golperu.html\" target=\"_blank\">Gol Perú<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"FIFA\"><a href=\"#\">");
document.writeln("ES Sétif vs. ES Tunis CAF Champions League");
document.writeln("<span class=\"t\">22:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"bein8.html\" target=\"_blank\">BeIN Sports Max 8 FR<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Central Córdoba vs. Arsenal Copa Liga Profesional");
document.writeln("<span class=\"t\">23:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"http://diexsport.herokuapp.com/tntsport.html\" target=\"_blank\">TNT Sports<span>Calidad 1080p</span></a>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Aldosivi vs. Rosario Central Copa Liga Profesional");
document.writeln("<span class=\"t\">23:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"http://diexsport.herokuapp.com/foxpremium.html\" target=\"_blank\">FOX Sports Premium<span>Calidad 1080p</span></a>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Los Andes vs. JJ Urquiza Primera B Metropolitana");
document.writeln("<span class=\"t\">23:05</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"tycsport2.html\" target=\"_blank\">TyC Sports<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"URU\"><a href=\"#\">");
document.writeln("Defensor Sporting vs Fénix");
document.writeln("<span class=\"t\">00:15</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"evento1.html\" target=\"_blank\">Star +<span>Calidad 1080p</span></a>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"WWE\"><a href=\"#\">");
document.writeln("WWE Smackdown Español");
document.writeln("<span class=\"t\">01:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"foxsport2.html\" target=\"_blank\">Fox Sports 2<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"AR\"><a href=\"#\">");
document.writeln("Newell's vs. Patronato Copa Liga Profesional");
document.writeln("<span class=\"t\">01:30</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"http://diexsport.herokuapp.com/foxpremium.html\" target=\"_blank\">FOX Sports Premium<span>Calidad 1080p</span></a>");
document.writeln("<li class=\"subitem1\"><a href=\"espn1p.html\" target=\"_blank\">ESPN<span>Calidad 1080p</span></a>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"NBA\"><a href=\"#\">");
document.writeln("NBA: Transmisión (<i style=\"color:red\">No Actualizado</i>)");
document.writeln("<span class=\"t\">01:00</span></a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal5/tnt01.html\" target=\"iframe\">TNT OP 1<span>Calidad 480p</span></a></li>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal5/tnt01.html\" target=\"iframe\">TNT OP 2<span>Calidad 720p</span></a></li>");
document.writeln("<p><strong><i style=\"color:red\">OPCIÓN M3U8:</strong></i> Para que esta opción funcione en PC, necesitás instalar la extensión <strong style=\"color:red\">Reproductor M3U8 - HLS Player</strong> en tu navegador. (<a href=\"https://chrome.google.com/webstore/detail/lcipembjfkmeggpihdpdgnjildgniffl\" target=\"iframe\">Google Chrome-Brave</a> / <a href=\"https://addons.mozilla.org/es/firefox/addon/native_hls_playback/\" target=\"iframe\">Mozilla Firefox</a>)</p>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li class=\"CH\"><a href=\"#\">	");
document.writeln("<span class=\"\"><i class=\"fa-solid fa-play\"></i> TV</span>Musica Las 24 Horas</a>");
document.writeln("<ul>");
document.writeln("<li class=\"subitem1\"><a href=\"/canal3/foxmix.html\" target=\"iframe\">Portal Fox mix<span>Calidad 720p</span></a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("</ul>");
}
